language: csharp

node_js: "8"
install: "npm install"
script: "npm test"

addons:
  apt:
    packages:
      - wine

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
cache:
  yarn: true
script:
    - npm run build
    - npm run setup