language: node_js

node_js:
  - '8'

addons:
  apt:
    packages:
      - wine
      - mono

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
cache:
  yarn: true
script:
    - npm run build
    - npm run setup